<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Cabin extends Model{
    public function elector(){
        return $this->belongsTo('App\Models\Elector');
    }
    public function votos(){
        return $this->hasMany('App\Models\Voto');
    }
}