<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Elector extends Model{
    public function cabins(){
        return $this->hasMany('App\Models\Cabin');
    }
}